export const CODE = 'CODE'
export const CODE_SUCCESS = 'CODE_SUCCESS'
export const CODE_ERROR = 'CODE_ERROR'
export const SLIDE_FADE_IN = 'SLIDE_FADE_IN'
export const SLIDE_FADE_OUT = 'SLIDE_FADE_OUT'
export const SLIDE_DISPLAY_FLEX = 'SLIDE_DISPLAY_FLEX'
